version: '3'


networks:
  rf_net:
    driver: bridge
    ipam:
      config:
      -
        subnet: 192.168.1.0/25

services:
  eureka:
    container_name: rf_eureka
    image: reservafacil/eureka
    ports:
      - "8761:8761"
    command: java -jar eureka-service-0.0.1-SNAPSHOT.jar
    networks:
      - rf_net
