version: '3'


networks:
  rf_net_local:
    driver: bridge
    ipam:
      config:
      -
        subnet: 172.16.1.0/24

services:
  dbTransferencia:
    container_name: db-transferencia
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    tty: true
    networks:
      - rf_net_local
  consul:
    container_name: consul
    image: consul
    hostname: consul
    ports:
      - "8500:8500"
    expose:
      - "8500"
    tty: true
    networks:
      - rf_net_local
  taxa:
    container_name: rf_taxa
    image: reservafacil/taxa
    hostname: taxa
    deploy:
      replicas: 2
    ports:
      - "8082:8082"
    expose:
      - "8082"
    tty: true
    command: java -jar taxa-app-0.0.1-SNAPSHOT.jar
    networks:
      - rf_net_local
  transferencia:
    container_name: rf_transferencia
    image: reservafacil/transferencia
    hostname: transferencia
    deploy:
      replicas: 5
    ports:
      - "8083:8083"
    expose:
      - "8083"
    tty: true
    command: java -jar transferencia-app-0.0.1-SNAPSHOT.jar
    networks:
      - rf_net_local


