version: '3'


networks:
  rf_net_local:
    driver: bridge
    ipam:
      config:
      -
        subnet: 172.16.1.0/24

services:
  dbTransferencia:
    container_name: db-transferencia
    image: postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    tty: true
    networks:
      - rf_net_local
  eureka:
    container_name: rf_eureka
    image: reservafacil/eureka
    hostname: eureka
    ports:
      - "8761:8761"
    expose:
      - "8671"
    tty: true
    command: java -jar eureka-service-0.0.1-SNAPSHOT.jar
    networks:
      - rf_net_local


