server:
  port: 8083
spring:
  datasource:
    generate-unique-name: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: transferencia-app
 
eureka: 
  client:
     serviceUrl:
       default: http://localhost:8761/eureka/ 


