version: '3.1'

networks:
  rf_net:
    driver: bridge
    ipam:
      config:
      -
        subnet: 192.168.2.0/25

services:
  dbTransferencia:
    container_name: db-transferencia
    image: reservafacil/postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
    ports:
      - 5432:5432
    networks:
      - rf_net 

