apiVersion: v1
kind: Pod
metadata:
  name: rf-pod
  namespace: reservafacil
spec:
  containers:
  - name: consul
    image: consul
    imagePullPolicy: IfNotPresent
  - name: taxa-app
    image: reservafacil/taxa
    imagePullPolicy: IfNotPresent

