apiVersion: v1
kind: Pod
metadata:
  name: rf-pod
  namespace: reservafacil
spec:
  containers:
  - name: taxa-app
    image: reservafacil/taxa
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        memory: "200Mi"
      requests:
        memory: "100Mi"
    command: ["java -jar taxa-app-0.0.1-SNAPSHOT.jar"]
    args: ["--vm", "1", "--vm-bytes", "150M", "--vm-hang", "1"]